### ISSUE TITLE
Fix VS Gallery link in readme.md

### ISSUE THREAD

**Issue by ylepikhov** [madskristensen/CommandTaskRunner#1]
Should be https://visualstudiogallery.msdn.microsoft.com/e6bf6a3d-7411-4494-8a1e-28c1a8c4ce99

**Comment by madskristensen** [comment]
This is a great opportunity to send a pull request. 

Go to the [readme.md](https://github.com/madskristensen/CommandTaskRunner/blob/master/README.md) page and click the edit icon on the upper right corner (make sure you are logged in to GitHub).

Then make the edit to the markdown page and click the green button at the bottom. No need to fork or clone anything to your local machine.

**Comment by ylepikhov** [comment]
Done. And thank you for this and other VS extensions.
