### ISSUE TITLE
Active build configuration

### ISSUE THREAD

**Issue by rvhelden** [madskristensen/CommandTaskRunner#11]
Is it possible to get the current buildconfiguration and pass it as an argument for example

{
  "commands": {
    "Demo": {
      "fileName": "powershell.exe",
      "workingDirectory": ".",
      "arguments": "-ExecutionPolicy Bypass -NonInteractive -File Demo.ps1 **$BuildConfiguration**"
    }
}

**Comment by madskristensen** [comment]
No, but that can be added

**Comment by rvhelden** [comment]
It would be nice to be able to do that so we can make a more flexible script
