### ISSUE TITLE
1.2.40 - VS2015/2017 - Doesn't discover the commands.json anymore.

### ISSUE THREAD

**Issue by Thieum** [madskristensen/CommandTaskRunner#20]
### Installed product versions
- Visual Studio: 2015 Pro / 2017 Pro
- This extension: 1.2.40

### Description
The extension doesn't discover the commands.json anymore. The commands list remains empty even with a commands.json available in the solution.

### Steps to recreate
1. Open a solution with an existing commands.json, and commands defined.
2. The commands list remains empty even when refreshing.

### Current behavior
The extension cannot find the command.json file.

### Expected behavior
The extension should be able to find the command.json file, and populate the commands list accordingly.

**Comment by twwilliams** [comment]
We see the same problem in VS 2017 Professional and Enterprise 15.8.3 and 15.8.5 (don't think anyone in our team is on 15.8.4).

**Comment by yepeekai** [comment]
It is simply not working at all in my case :(
Does anyone still have a version before 1.2.40?

**Comment by madskristensen** [comment]
This should be fixed in version 1.2.41. Please let me know if it works for you as it does for me.

**Comment by yepeekai** [comment]
It works for me too.  Thanks for the fast fix!

**Comment by Thieum** [comment]
Doesn't work for us on both VS2015 / 2017.
The output shows:

`Failed to run "C:\Users\xxx\commands.json"...`

Here is the content of my json file:

```
{
  "commands": {
    "ReleaseCandidate": {
        "fileName": "powershell.exe",
        "workingDirectory": ".",
        "arguments": "-File Scripts\\ReleaseCandidate.ps1"
    },
    "StartVirtualMetalSensor": {
        "fileName": "powershell.exe",
        "workingDirectory": ".",
        "arguments": "-command &\"{ start powershell {.\\Scripts\\\\StartVirtualMetalSensor.ps1} }\""
    },
    "Clean": {
        "fileName": "powershell.exe",
        "workingDirectory": ".",
        "arguments": "-command &\"{ (Importer).ImportPowershellHelpers('2'); CleanSolution '.\\' }\""
    }
  }
}

```
The file loads if I comment all my commands.
