### ISSUE TITLE
1.2.41 - VS2015/2017 - Doesn't discover the commands.json anymore in C++/CLR and C# mixed solutions.

### ISSUE THREAD

**Issue by Thieum** [madskristensen/CommandTaskRunner#21]
### Installed product versions
- Visual Studio: 2015 Enterprise / 2017 Pro
- This extension: 1.2.41

### Description
Follow up of #20 . The fix helped for .NET solutions with only C# projects, but doesn't with solutions where there are C++/CLR projects mixed with C# projects.

### Steps to recreate
1. Create a new solution.
2. Add a new C++ / CLR library project
3. Add a new winforms project
4. Make the winforms project depend on the C++/CLR one
5. Close the solution
6. Open the solution
7. Create an empty batch file in the WinForms project folder
8. Add the batch file to the project
9. Add it to the task runner.

### Current behavior
The json file will be succesfully created and added to the solution, but it will be not be loaded by the extension. The following error message will be output in the console:

`Failed to run "C:\Users\xxx\Documents\Visual Studio 2015\Projects\ClassLibrary2\commands.json"...`

The same file will successfully load in a solution where there are only C# projects.

### Expected behavior
The json file should be able to load like in the other kind of solutions.

**Comment by Mevos126** [comment]
I'm having the same problem with both Visual Studio 2015 and 2017. Purely C# solutions don't work, but C++/CLR solutions will work.

**Comment by spayton** [comment]
I'm getting the same problem, "Failed to run..." message in output window upon VS launch for a web site project (solution contains 2 web site projects).  The commands.json doesn't show in the Task Runner Explorer.

**Comment by Thieum** [comment]
A simpler scenario is having just one C++ project in a solution - it won't work either.

**Comment by Thieum** [comment]
@spayton I managed to fix the issue for C++ projects, but I'm not sure for web projects. If it's like c++ projects, one of the properties that the tool tries to read from the project must be invalid. I found my fix by setting a breakpoint on https://github.com/madskristensen/CommandTaskRunner/blob/master/src/TaskRunner/TaskRunnerProvider.cs#L109 . Maybe try the same with your projects, and see what fails to load after that point.

**Comment by spayton** [comment]
The 1.2.43 nightly still doesn't work for my web project.  Same thing happens, the "Failed to run xxx\commands.json" and no commands.json in the task runner.

**Comment by spayton** [comment]
Project is a basic website, just files on the disk, it does have a target .net 4.5 framework though not used.  The problem occurs on both VS2015ce and vs2017ce.

**Comment by Thieum** [comment]
@spayton Trying to reproduce with the correct project template, would that be "ASP.NET Empty Web Site"?

![image](https://user-images.githubusercontent.com/944894/50903388-ac45ab00-13eb-11e9-8ed6-7a5d4d24a582.png)

Or maybe you can share an example solution in a github repo.

**Comment by spayton** [comment]
The project was generated with this sequence:

File -> Add -> Existing Web Site

then choose the 'File System' method and just point it at a directory

**Comment by Thieum** [comment]
@spayton go it fixed I think in #26 - I had an issue as well with some other kind of projects - hopefully it's the good one this time for you as well :)

**Comment by spayton** [comment]
nightly v1.2.45 is now working correctly for web folder projects
