### ISSUE TITLE
Are visual c/c++ projects (.vcxproj) supported?  

### ISSUE THREAD

**Issue by solvingj** [madskristensen/CommandTaskRunner#35]
### Installed product versions
- Visual Studio: [example 2017 Professional]
- This extension: [example 1.1.41]

### Description
Task Runner Explorer is always empty in my `.vcxproj`, even when i add `commands.json` from the `README.md` of this repo to the solution project root.  After looking at source code, I found this line and suspect that it's just silently unsupported for some undocumented reason: 

https://github.com/madskristensen/CommandTaskRunner/blob/de2b303e603c341dad3a5133e2b877352a8d3b32/src/TaskRunner/TaskRunnerProvider.cs#L109

### Steps to recreate
1. Create or open a visual c/c++ project (`.vcxproj`)
2. Add a `commands.json` file from the readme.
3. Open Task Runner Explorer
4. Refresh, look for tasks. 

### Current behavior
The Task Runner Explorer window shows "No task runner configurations were found" message.  The dropdown box is empty and deactivated. 

### Expected behavior
After adding `commands.json`, I expected that I would be able to run the commands described within it.  Seems relatively simple.  

If it's not supported, it would be nice to understand why, and I suggest documenting this limitation on the readme.  If it's possible that support could be added but it will just take some work, then I can rename this ticket to "feature request...".

**Comment by Thieum** [comment]
@solvingj I added this fix, as the vcxproj projects don't propagate the same info through the API, and it would throw a NRE further down the logic.

There are other kind of projects that are not supported actually, for which I filtered here:
https://github.com/madskristensen/CommandTaskRunner/blob/de2b303e603c341dad3a5133e2b877352a8d3b32/src/TaskRunner/TaskRunnerProvider.cs#L122

The code would actually work if you have at least one .net project.

For a solution that has only vcxproj projects, you would need to remove the filter and find the best way to handle the missing properties. 

In the mean time, I could send a PR to document the choices I made from #20 #21 and #25

**Comment by solvingj** [comment]
Wow, thanks so much for the timely response.  Let me see if I can ponder up any workarounds for the missing properties.

**Comment by solvingj** [comment]
Upon cursory review, the filtering of `vcxproj` and subsequent dropping of support was due to errors about missing properties.  However, from what I saw, these errors were borderline cosmetic and should have been easily by-passable or otherwise resolvable without dropping `vcxproj`, and the issue was simply that nobody tried to resolve them. 

I'm going to try to resolve all the errors in a new PR, and effectively revert the filter from PR: https://github.com/madskristensen/CommandTaskRunner/pull/23

**Comment by solvingj** [comment]
@Thieum I am able to run the extension and execute tasks in debug mode without any errors.  Can you recall any specific places where you got NRE?

**Comment by Thieum** [comment]
@solvingj if you want to reproduce the state of the code as it was before, you need to remove both checks I added later:
![image](https://user-images.githubusercontent.com/944894/59621754-edaa5700-90fd-11e9-8349-f4fc49746d2c.png)
Which are sufficient to work with vcxproj, so the explicit filter could have been removed. You would have access to the tasks as intended in a solution with only vcprojs. The build events may not work, that's the part I'm less familiar with.

**Comment by solvingj** [comment]
Ok, I see, yes that would be best.  Can you submit a PR removing the explicit filter, or would you like me to submit one?

**Comment by Thieum** [comment]
@solvingj I will submit a PR - would you consider it would fix this issue, even if the build events may not work (I won't be able to test those in a timely manner)?

**Comment by solvingj** [comment]
Yes, this will enable us to use the on-doubleclick tasks, and the other null checks protect from runtime errors.  It would be a good fix.
