### ISSUE TITLE
Add VS 2022 compatibility

### ISSUE THREAD

**Issue by danreg** [madskristensen/CommandTaskRunner#53]
It would be great to have this extension in Visual Studio 2022. Could you please update?

**Comment by Thieum** [comment]
@danreg it's not available yet on the official gallery, but you can already get it through the VSIX Gallery there: https://www.vsixgallery.com/extension/fc1aafb2-321e-41bd-ac37-03b09ea8ef31

**Comment by mroberts-btg** [comment]
I've been trying to work with that one, but I get "No task runner providers were found".  I DO have a commands.json in the same folder as my solution.
![image](https://user-images.githubusercontent.com/13124722/141151389-aca575ac-68f0-4b9a-90df-d60b08a8e712.png)

**Comment by redwyre** [comment]
> I've been trying to work with that one, but I get "No task runner providers were found". I DO have a commands.json in the same folder as my solution. ![image](https://user-images.githubusercontent.com/13124722/141151389-aca575ac-68f0-4b9a-90df-d60b08a8e712.png)

Same using 1.3.96 from vsixgallery, working in 2019, nothing in 2022.

**Comment by VivPat** [comment]
> I've been trying to work with that one, but I get "No task runner providers were found". I DO have a commands.json in the same folder as my solution. ![image](https://user-images.githubusercontent.com/13124722/141151389-aca575ac-68f0-4b9a-90df-d60b08a8e712.png)

I can concur that although I have installed the  VSIX, I am unable to use the CommandTaskRunner in VS 2022 v17.0.0

![image](https://user-images.githubusercontent.com/8534371/141531958-e254aa34-de63-455c-a1c5-036d6afc8ff8.png)

**Comment by madskristensen** [comment]
Try it out here: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CommandTaskRunner64

**Comment by redwyre** [comment]
Thanks Mads, the new extension is loading the commands now, however I am having an issue running powershell scripts.

Previously I was using `C:\\Windows\\SysNative\\WindowsPowerShell\\v1.0\\powershell.exe` to run 64bit powershell, however it seems this only works for 32 bit processes and it seems to do nothing - but closing the tab in this state crashes visual studio. I notice the docs say ps1 is "supported" but I'm not sure exactly what that means...

**Comment by VivPat** [comment]
Thank you for this. All seems to be working perfectly.
As always, you rock.
